### ISSUE TITLE
unsupported operand type(s) for |: 'types.GenericAlias' 

### ISSUE THREAD

**Issue by imperator-maximus** [Intersection98/ComfyUI_MX_post_processing-nodes#1]
Hello,

after installation (I tried with manager and alternative git clone + pip install) I am getting:

> Traceback (most recent call last):
>   File "E:\sd\ComfyUI\nodes.py", line 1887, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "E:\SD\ComfyUI\custom_nodes\ComfyUI_MX_post_processing-nodes\__init__.py", line 1, in <module>
>     from .MX_post_processing_nodes import NODE_CLASS_MAPPINGS
>   File "E:\SD\ComfyUI\custom_nodes\ComfyUI_MX_post_processing-nodes\MX_post_processing_nodes.py", line 14, in <module>
>     size: tuple[int] | tuple[int, int],
> TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

So it does not work at all.

btw: there is a typo in Readme - it should be
"git clone https://github.com/Intersection98/ComfyUI_MX_post_processing-nodes.git"

Thank you!

**Comment by imperator-maximus** [comment]
I found it myself: I had older Python version. I just upgraded to 3.11.9 and now it works :)

**Comment by imperator-maximus** [comment]
solved
